CXX := msp430-elf-g++
SIZE := msp430-elf-size
OBJCOPY := msp430-elf-objcopy
    
CXXFLAGS += -mmcu=msp430fr2355
CXXFLAGS += --std=c++17
CXXFLAGS += -Os
CXXFLAGS += -ffunction-sections
CXXFLAGS += -fdata-sections
CXXFLAGS += -flto
CXXFLAGS += -DEMBEDDED_BUILD
CXXFLAGS += -DPLATFORM_MSP430FR2355
#CXXFLAGS += -DF_CPU=16000000UL
CXXFLAGS += -IC:\ti\msp430-gcc\include

LDFLAGS += -mmcu=msp430fr2355
LDFLAGS += -TC:\ti\msp430-gcc\include\msp430fr2355.ld
LDFLAGS += -LC:\ti\msp430-gcc\include
LDFLAGS += -Os
LDFLAGS += -Wl,--gc-sections
LDFLAGS += -flto
LDFLAGS += -Wl,-Map,$(OUTPUTDIR)/$(APPLICATION).map

APP_OBJ += $(OBJECTDIR)/Source/Platform/MSP430FR2355/MSP430FR2355Platform.o
APP_OBJ += $(OBJECTDIR)/Source/Platform/MSP430FR2355/MSP430FR2355SPI.o
APP_OBJ += $(OBJECTDIR)/Source/Platform/MSP430FR2355/MSP430FR2355UART.o

BUILD_TARGETS += $(OUTPUTDIR)/$(APPLICATION).elf
BUILD_TARGETS += $(OUTPUTDIR)/$(APPLICATION).hex
BUILD_TARGETS += $(OUTPUTDIR)/$(APPLICATION).bin

FLASH_TOOL_FILE := $(OUTPUTDIR)/$(APPLICATION).hex
FLASH_TOOL := MSP430Flasher
FLASH_ARGS := -i USB
FLASH_ARGS += -n MSP430FR2355
FLASH_ARGS += -w $(OUTPUTDIR)/$(APPLICATION).hex
FLASH_ARGS += -e ERASE_ALL
FLASH_ARGS += -v
FLASH_ARGS += -z [VCC]